"""add model enabled

Revision ID: 39ac6cd83e6b
Revises: 00d779c74806
Create Date: 2025-05-26 14:05:11.565195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ac6cd83e6b'
down_revision: Union[str, None] = '00d779c74806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_categories', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('prompt_categories', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index('prompt_categories_id_idx', table_name='prompt_categories')
    op.add_column('prompts', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_constraint('prompts_category_name_fkey', 'prompts', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_category_name_fkey'), 'prompts', 'prompt_categories', ['category_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('prompts', 'for_image')
    op.drop_column('prompts', 'for_video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('for_video', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('prompts', sa.Column('for_image', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('prompts_category_name_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key('prompts_category_name_fkey', 'prompts', 'prompt_categories', ['category_name'], ['name'], ondelete='CASCADE')
    op.drop_column('prompts', 'enabled')
    op.create_index('prompt_categories_id_idx', 'prompt_categories', ['id'], unique=False)
    op.alter_column('prompt_categories', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('prompt_categories', 'enabled')
    # ### end Alembic commands ###
