"""add user_inputs

Revision ID: 8d0fc9169504
Revises: a6d5de3bdcfe
Create Date: 2025-05-01 12:22:50.457050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0fc9169504'
down_revision = 'a6d5de3bdcfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_userinputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_userinputs_id'), 'prompt_userinputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_userinputs_id'), table_name='prompt_userinputs')
    op.drop_table('prompt_userinputs')
    # ### end Alembic commands ###
