"""refactor

Revision ID: a6800518a3f8
Revises: e37acf4910b8
Create Date: 2025-05-17 21:02:30.214486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages
from sqlalchemy.dialects import postgresql

from src.core.filesystem_storage import storage

# revision identifiers, used by Alembic.
revision: str = 'a6800518a3f8'
down_revision: Union[str, None] = 'e37acf4910b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_index('ix_task_requests_id', table_name='task_requests')
#    op.drop_table('task_requests')
#    op.drop_index('ix_task_images_id', table_name='task_images')
#    op.drop_table('task_images')
    op.drop_constraint('prompts_category_name_fkey', 'prompts', type_='foreignkey')
    op.alter_column('prompts', 'category_name',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(op.f('prompts_category_name_fkey'), 'prompts', 'prompt_categories', ['category_name'], ['name'], ondelete='CASCADE')
    op.alter_column('prompts', 'image',
               existing_type=postgresql.BYTEA(),
               type_=fastapi_storages.integrations.sqlalchemy.ImageType(storage),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tasks_id_idx'), table_name='tasks')
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.drop_index(op.f('task_items_id_idx'), table_name='task_items')
    op.create_index('ix_task_items_id', 'task_items', ['id'], unique=False)
    op.alter_column('task_items', 'result_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('prompts_category_name_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key('prompts_category_name_fkey', 'prompts', 'prompt_categories', ['category_name'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('prompts_id_idx'), table_name='prompts')
    op.create_index('ix_prompts_id', 'prompts', ['id'], unique=False)
    op.alter_column('prompts', 'category_name',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('prompts', 'image',
               existing_type=fastapi_storages.integrations.sqlalchemy.ImageType(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_index(op.f('prompt_userinputs_id_idx'), table_name='prompt_userinputs')
    op.create_index('ix_prompt_userinputs_id', 'prompt_userinputs', ['id'], unique=False)
    op.drop_index(op.f('prompt_categories_id_idx'), table_name='prompt_categories')
    op.create_index('ix_prompt_categories_id', 'prompt_categories', ['id'], unique=False)
    op.drop_index(op.f('contexts_id_idx'), table_name='contexts')
    op.create_index('ix_contexts_id', 'contexts', ['id'], unique=False)
    op.drop_index(op.f('context_entitys_id_idx'), table_name='context_entitys')
    op.create_index('ix_context_entitys_id', 'context_entitys', ['id'], unique=False)
    op.alter_column('context_entitys', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'assistant', 'system', name='contextentityrole'),
               existing_nullable=False)
    op.alter_column('context_entitys', 'content_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('image', 'text', name='contextentitycontenttype'),
               existing_nullable=False)
    op.create_table('task_images',
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_images_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_images_pkey')
    )
    op.create_index('ix_task_images_id', 'task_images', ['id'], unique=False)
    op.create_table('task_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schema', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_requests_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_requests_pkey')
    )
    op.create_index('ix_task_requests_id', 'task_requests', ['id'], unique=False)
    # ### end Alembic commands ###
