"""make inputs models many2many

Revision ID: d8499551eadc
Revises: f732c1e10a56
Create Date: 2025-05-21 12:40:14.351372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8499551eadc'
down_revision: Union[str, None] = 'f732c1e10a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts_userinputs_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_userinput_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('prompts_userinputs_association_prompt_id_fkey')),
    sa.ForeignKeyConstraint(['prompt_userinput_id'], ['prompt_userinputs.id'], name=op.f('prompts_userinputs_association_prompt_userinput_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prompts_userinputs_association_pkey'))
    )
    op.drop_constraint('prompt_userinputs_prompt_id_fkey', 'prompt_userinputs', type_='foreignkey')
    op.drop_column('prompt_userinputs', 'prompt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_userinputs', sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('prompt_userinputs_prompt_id_fkey', 'prompt_userinputs', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.drop_table('prompts_userinputs_association')
    # ### end Alembic commands ###
