"""add task_items used_tokens

Revision ID: f732c1e10a56
Revises: a6800518a3f8
Create Date: 2025-05-20 22:16:23.057193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f732c1e10a56'
down_revision: Union[str, None] = 'a6800518a3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('used_tokens', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_items', 'used_tokens')
    # ### end Alembic commands ###
