"""add context

Revision ID: 44216a5e4f34
Revises: 8d0fc9169504
Create Date: 2025-05-12 18:36:38.126167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44216a5e4f34'
down_revision = '8d0fc9169504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contexts_id'), 'contexts', ['id'], unique=False)
    op.create_table('context_entitys',
    sa.Column('content_type', sa.Enum('image', 'text', name='contextentitycontenttype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='contextentityrole'), nullable=False),
    sa.Column('context_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_entitys_id'), 'context_entitys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_entitys_id'), table_name='context_entitys')
    op.drop_table('context_entitys')
    op.drop_index(op.f('ix_contexts_id'), table_name='contexts')
    op.drop_table('contexts')
    # ### end Alembic commands ###
