"""add category

Revision ID: e37acf4910b8
Revises: e9e296c52ed2
Create Date: 2025-05-13 17:33:00.042994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37acf4910b8'
down_revision = 'e9e296c52ed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_prompt_categories_id'), 'prompt_categories', ['id'], unique=False)
    op.add_column('prompts', sa.Column('category_name', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'prompts', 'prompt_categories', ['category_name'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_column('prompts', 'category_name')
    op.drop_index(op.f('ix_prompt_categories_id'), table_name='prompt_categories')
    op.drop_table('prompt_categories')
    # ### end Alembic commands ###
