"""add task context_id

Revision ID: e9e296c52ed2
Revises: 44216a5e4f34
Create Date: 2025-05-12 20:08:15.867705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e296c52ed2'
down_revision = '44216a5e4f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('context_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'contexts', ['context_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'context_id')
    # ### end Alembic commands ###
